package aliceGlow.example.aliceGlow.service;

import aliceGlow.example.aliceGlow.dto.auth.AuthResponse;
import aliceGlow.example.aliceGlow.dto.auth.LoginDTO;
import aliceGlow.example.aliceGlow.infra.security.JwtService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("AuthService Tests")
class AuthServiceTest {

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private JwtService jwtService;

    @Mock
    private Authentication authentication;

    @InjectMocks
    private AuthService authService;

    private LoginDTO loginDTO;
    private UserDetails userDetails;
    private String generatedToken;

    @BeforeEach
    void setUp() {
        loginDTO = new LoginDTO("test@example.com", "password123");
        userDetails = new User("test@example.com", "password123", new ArrayList<>());
        generatedToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...token_jwt";
    }

    @Test
    @DisplayName("Should authenticate user and return token when login is successful")
    void shouldLoginSuccessfully() {
        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(userDetails);
        when(jwtService.generateToken(userDetails))
                .thenReturn(generatedToken);

        AuthResponse response = authService.login(loginDTO);

        assertNotNull(response);
        assertEquals(generatedToken, response.token());

        verify(authenticationManager, times(1))
                .authenticate(any(UsernamePasswordAuthenticationToken.class));
        verify(authentication, times(1)).getPrincipal();
        verify(jwtService, times(1)).generateToken(userDetails);
    }

    @Test
    @DisplayName("Should call authenticationManager with correct email and password")
    void shouldAuthenticateWithCorrectCredentials() {
        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(userDetails);
        when(jwtService.generateToken(userDetails))
                .thenReturn(generatedToken);

        authService.login(loginDTO);

        verify(authenticationManager).authenticate(any(UsernamePasswordAuthenticationToken.class));
    }

    @Test
    @DisplayName("Should return token generated by JwtService")
    void shouldReturnGeneratedToken() {
        String expectedToken = "new_generated_token_123";
        
        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(userDetails);
        when(jwtService.generateToken(userDetails))
                .thenReturn(expectedToken);

        AuthResponse response = authService.login(loginDTO);

        assertEquals(expectedToken, response.token());
    }

    @Test
    @DisplayName("Should call JwtService.generateToken with authenticated user details")
    void shouldGenerateTokenWithUserDetails() {
        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(userDetails);
        when(jwtService.generateToken(userDetails))
                .thenReturn(generatedToken);

        authService.login(loginDTO);

        verify(jwtService).generateToken(userDetails);
    }

    @Test
    @DisplayName("Should return AuthResponse with token not null")
    void shouldReturnNonNullAuthResponse() {
        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(userDetails);
        when(jwtService.generateToken(userDetails))
                .thenReturn(generatedToken);

        AuthResponse response = authService.login(loginDTO);

        assertNotNull(response);
        assertNotNull(response.token());
        assertFalse(response.token().isBlank());
    }

    @Test
    @DisplayName("Should handle different user credentials")
    void shouldHandleDifferentCredentials() {
        LoginDTO differentLogin = new LoginDTO("different@example.com", "different_password");
        UserDetails differentUserDetails = new User("different@example.com", "different_password", new ArrayList<>());
        String differentToken = "different_token_456";

        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        when(authentication.getPrincipal())
                .thenReturn(differentUserDetails);
        when(jwtService.generateToken(differentUserDetails))
                .thenReturn(differentToken);

        AuthResponse response = authService.login(differentLogin);

        assertEquals(differentToken, response.token());
        verify(jwtService).generateToken(differentUserDetails);
    }
}
